# Generated by Django 4.1.2 on 2022-10-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0002_artist_album"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=75)),
                ("slug", models.SlugField(blank=True, max_length=75, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
