# Generated by Django 4.1.2 on 2022-10-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0003_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="genre",
            field=models.ManyToManyField(related_name="albums", to="music.genre"),
        ),
    ]
